# Generated by Django 2.2.9 on 2020-01-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landmark',
            options={'ordering': ['start_date_time']},
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
