# Generated by Django 2.2.9 on 2020-01-28 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0002_profile_joblocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicationDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='dueDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='joblisting',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='application',
            name='resumekey',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='notes',
            field=models.TextField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='followup',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='landmark',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
