# Generated by Django 2.2.9 on 2020-01-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0003_auto_20200128_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='landmark',
            old_name='datetime',
            new_name='start_date_time',
        ),
        migrations.AddField(
            model_name='landmark',
            name='end_date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
