# Generated by Django 2.2.9 on 2020-01-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_tracker', '0004_auto_20200129_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='job_tracker.Application'),
        ),
    ]
